config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  get 'favorites/controller'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :customers, controllers: {
    registrations: 'front/registrations',
    sessions: 'front/sessions'
  }

  devise_scope :customer do
    post 'front/guest_sign_in' => 'front/sessions#new_guest'
  end

  root 'homes#top'
  get '/homes/about' => 'homes#about'

  namespace :front do
    resources :customers
    get '/customers/:id/follower' => 'customers#follower', as: 'follower'
    get '/customers/:id/followed' => 'customers#followed', as: 'followed'
    get '/customers/:id/favoriteartist' => 'customers#favoriteartist', as: 'favoriteartist'
    get '/customers/:id/favoritesong' => 'customers#favoritesong', as: 'favoritesong'
    get '/customers/:id/customerblog' => 'customers#customerblog', as: 'customerblog'
    resources :artists, only: [:index, :show] do
      resource :favorite_artists, only: [:create, :destroy]
      collection do
        get 'search'
      end
    end
    resources :songs, only: [:index, :show] do
      collection do
        get 'search'
      end
      resource :favorite_songs, only: [:create, :destroy]
    end
    resources :communities, only: [:index, :show] do
      collection do
        get 'favorite_index'
      end
    end
    resources :blogs, except: [:new, :show]
    post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
    post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
  end

  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'

end

app/models/artist.rb
class Artist < ApplicationRecord
  
  mount_uploader :image_id, ImagesUploader
  has_many :songs

  has_many :favorite_artists, dependent: :destroy
  
  def favorited_by?(customer)
    favorite_artists.where(customer_id: customer.id).exists?
  end

end

app/controllers/front/artists_controller.rb
class Front::ArtistsController < ApplicationController

  def index
    @artists = Artist.all.page(params[:page]).per(6)
    @all_ranks = Artist.find(FavoriteArtist.group(:artist_id).order('count(artist_id) desc').limit(3).pluck(:artist_id))
    @new_artists = Artist.all.order("created_at desc").page(params[:page]).per(4)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @artist = Artist.find(params[:id])
    @items = RakutenWebService::Ichiba::Item.search(keyword: @artist.name, genreId: '101311')
  end

  def search
    @artists = Artist.where('name LIKE(?)', "%#{params[:keyword]}%")
  end

end

app/controllers/front/blogs_controller.rb
class Front::BlogsController < ApplicationController

  before_action :find_blog, only: [:edit, :update, :destroy]
  before_action :set_customer, only: [:index, :create, :update]

  def index
    @blog = Blog.new
    @blogs = Blog.where(customer_id: current_customer.id)
                 .order("created_at DESC")
                 .page(params[:page]).per(2)
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.customer_id = current_customer.id
    @blogs = Blog.where(customer_id: current_customer.id)
                 .order("created_at DESC")
                 .page(params[:page]).per(2)

    begin
      @blog.save!
    rescue ActiveRecord::RecordInvalid
      flash.now[:alert] = '投稿に失敗しました'
      return render :index
    rescue => e
      flash.now[:alert] = '投稿に失敗しました'
      logger.error e
      return render :index
    end

    flash[:notice] = '記事が投稿されました'
    redirect_to front_blogs_path
  end

  def edit
    return redirect_to front_blogs_path if @blog.customer_id != current_customer.id
    render :edit
  end

  def update
    return redirect_to front_blogs_path if @blog.customer_id != current_customer.id

    @blogs = Blog.where(customer_id: current_customer.id)
                 .order("created_at DESC")
                 .page(params[:page]).per(2)

    begin
      @blog.update!(blog_params)
    rescue ActiveRecord::RecordInvalid
      flash[:alert] = '更新に失敗しました'
      return redirect_to front_blogs_path
    rescue => e
      flash.now[:alert] = '更新に失敗しました'
      logger.error e
      @blog = Blog.new
      return render :index
    end

    flash[:notice] = '記事が更新されました'
    redirect_to front_blogs_path
  end

  def destroy
    return redirect_to front_blogs_path if @blog.customer_id != current_customer.id

    begin
      @blog.destroy!
    rescue => e
      flash.now[:alert] = '削除に失敗しました'
      logger.error e
      return render :index
    end

    flash[:notice] = '記事が削除されました'
    redirect_to front_blogs_path
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :content, :image_id, :start_time)
  end

  def find_blog
    @blog = Blog.find(params[:id])
  end

  def set_customer
    @customer = current_customer
  end

end

app/controllers/front/communities_controller.rb
class Front::CommunitiesController < ApplicationController

  def index
    @communities = Community.page(params[:page]).per(10).order(created_at: :desc)
  end

  def show
    @community = Community.find(params[:id])
    @chats = @community.chats.includes(:customer).page(params[:page]).per(10)
  end

  def favorite_index
  end

end

app/controllers/front/customers_controller.rb
class Front::CustomersController < ApplicationController

  before_action :find_customer, only: [:show, :edit, :update, :destroy, :follower, :followed,
                                       :favoriteartist, :favoritesong, :customerblog]

  def show
  end

  def edit
    return redirect_to front_customer_path(current_customer) if @customer.id != current_customer.id
    render :edit
  end

  def update
    return redirect_to front_customer_path(current_customer) if @customer.id != current_customer.id

    begin
      @customer.update!(customer_params)
    rescue ActiveRecord::RecordInvalid
      flash.now[:alert] = '登録情報の更新に失敗しました'
      return render :edit
    rescue => e
      flash.now[:alert] = '登録情報の更新に失敗しました'
      logger.error e
      return render :edit
    end

    flash[:notice] = '登録情報が更新されました'
    redirect_to front_customer_path(@customer.id)
  end

  def follower
    @customers = @customer.follower
  end

  def followed
    @customers = @customer.followed
  end

  def favoriteartist
  end

  def favoritesong
  end

  def customerblog
    @blogs = Blog.where(customer_id: find_customer)
                 .order("created_at DESC")
                 .page(params[:page]).per(2)
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana,
                                     :email, :nickname, :image_id, :password, :password_confirmation)
  end

  def find_customer
    @customer = Customer.find(params[:id])
  end

end

app/controllers/front/favorite_artists_controller.rb
class Front::FavoriteArtistsController < ApplicationController

  before_action :find_artist, only: [:create, :destroy]

  def create
    favorite_artist = current_customer.favorite_artists.new(artist_id: @artist.id)

    begin
      favorite_artist.save!
    rescue => e
      respond_to do |format| 
        format.js {flash.now[:alert] = '登録に失敗しました'}
      end
      logger.error e
      return
    end

    respond_to do |format| 
      format.js {flash.now[:notice] = 'お気に入りに登録しました'}
    end
  end

  def destroy
    favorite_artist = current_customer.favorite_artists.find_by(artist_id: @artist.id)

    begin
      favorite_artist.destroy!
    rescue => e
      respond_to do |format| 
        format.js {flash.now[:alert] = '登録に失敗しました'}
      end
      logger.error e
      return
    end

    respond_to do |format| 
      format.js {flash.now[:notice] = 'お気に入りを解除しました'}
    end
  end

  private
  
  def find_artist
    @artist = Artist.find(params[:artist_id])
  end

end

app/controllers/front/favorite_songs_controller.rb
class Front::FavoriteSongsController < ApplicationController

  before_action :find_song, only: [:create, :destroy]

  def create
    favorite_song = current_customer.favorite_songs.new(song_id: @song.id)

    begin
      favorite_song.save!
    rescue => e
      respond_to do |format| 
        format.js {flash.now[:alert] = '登録に失敗しました'}
      end
      logger.error e
      return
    end

    respond_to do |format| 
      format.js {flash.now[:notice] = 'お気に入りに登録しました'}
    end
  end

  def destroy
    favorite_song = current_customer.favorite_songs.find_by(song_id: @song.id)

    begin
      favorite_song.destroy!
    rescue => e
      respond_to do |format| 
        format.js {flash.now[:alert] = '登録に失敗しました'}
      end
      logger.error e
      return
    end

    respond_to do |format| 
      format.js {flash.now[:notice] = 'お気に入りを解除しました'}
    end
  end

  private

  def find_song
    @song = Song.find(params[:song_id])
  end

end

app/controllers/front/registrations_controller.rb
class Front::RegistrationsController < Devise::RegistrationsController

  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

end

app/controllers/front/relationships_controller.rb
class Front::RelationshipsController < ApplicationController

  def follow
    begin
      current_customer.follow!(params[:id])
    rescue => e
      flash.now[:alert] = 'ユーザーのフォローに失敗しました'
      logger.error e
      return redirect_to request.referer
    end

    flash[:notice] = 'ユーザーをフォローしました'
    redirect_to request.referer
  end

  def unfollow
    begin
      current_customer.unfollow!(params[:id])
    rescue => e
      flash.now[:alert] = 'フォローの解除に失敗しました'
      logger.error e
      return redirect_to request.referer
    end

    flash[:notice] = 'フォローを解除しました'
    redirect_to request.referer
  end

end

app/controllers/front/sessions_controller.rb
class Front::SessionsController < Devise::SessionsController

  def new_guest
    customer = Customer.guest
    sign_in customer
    redirect_to front_customer_path(current_customer), notice: 'ゲストユーザーとしてログインしました'
  end

end

app/controllers/front/songs_controller.rb
class Front::SongsController < ApplicationController

  def index
    @songs = Song.all.page(params[:page]).per(6)
    @all_ranks = Song.find(FavoriteSong.group(:song_id).order('count(song_id) desc').limit(3).pluck(:song_id))
    @new_songs = Song.all.order("created_at desc").page(params[:page]).per(4)
    respond_to do |format|
      format.html
      format.js
    end

    if params[:genre_id]
      @genre = Genre.find(params[:genre_id])
      @songs = @genre.songs.page(params[:page]).per(6).order(created_at: :desc).all
      render :genre_songs
    end
  end

  def show
    @song = Song.find(params[:id])
  end

  def search
    @songs = Song.where('name LIKE(?)', "%#{params[:keyword]}%")
  end

end

app/helpers/front/artists_helper.rb
module Front::ArtistsHelper
end

app/helpers/front/blogs_helper.rb
module Front::BlogsHelper
end

app/helpers/front/communities_helper.rb
module Front::CommunitiesHelper
end

app/helpers/front/customers_helper.rb
module Front::CustomersHelper
end

app/helpers/front/favorite_artists_helper.rb
module Front::FavoriteArtistsHelper
end

app/helpers/front/favorite_songs_helper.rb
module Front::FavoriteSongsHelper
end

app/helpers/front/registrations_helper.rb
module Front::RegistrationsHelper
end

app/helpers/front/relationships_helper.rb
module Front::RelationshipsHelper
end

app/helpers/front/sessions_helper.rb
module Front::SessionsHelper
end

app/views/front/artists/_artists.html.erb
<% @artists.each do |artist| %>
<% if artist.is_active == true %>
  <div class="flex">
    <div class="artist_box">
      <div class="shadow_box">
        <%= image_tag artist.image_id.to_s %>
      </div>
      <br>
      <%= artist.name %>
      <br>
      <a href="/front/artists/<%= artist.id %>" class="btn btn_viewmore"><span>VIEW MORE</span></a>
      <div class="artist_<%= artist.id %>">
        <%= render 'front/artists/favorite', artist: artist, locals: {artist: artist} %>
      </div>
    </div>
  </div>
<% end %>
<% end %>
<br>
<%= paginate @artists, remote: true %>
<br>

app/views/front/artists/_favorite.html.erb
<% if artist.favorited_by?(current_customer) %>
  <%= link_to front_artist_favorite_artists_path(artist), method: :delete, remote: true do %>
    ❤︎<%= artist.favorite_artists.count %>
  <% end %>
  <% else %>
    <%= link_to front_artist_favorite_artists_path(artist), method: :post, remote: true do %>
      ♡<%= artist.favorite_artists.count %>
  <% end %>
<% end %>

<% if flash.any? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      <% key = "success" if key == "notice" %>
      <% key = "error" if key == "alert" %>
      toastr['<%= key %>']('<%= value %>');
    <% end %>
  </script>
<% end %>

app/views/front/artists/_new_artists.html.erb
<% @new_artists.each.with_index(1) do |artist, i| %>
<div class="flex">
  <div class="new_artist_box">
    <div class="new_shadow_box">
      <%= image_tag artist.image_id.to_s, :size => "150x150" %>
    </div>
    <br>
    <p class="new_artist_name"><%= link_to artist.name, front_artist_path(artist.id) %></p>
  </div>
</div>
<% end %>
<br>
<%= paginate @new_artists, remote: true %>

app/views/front/artists/index.html.erb
<div align="center">
  <%= form_with(url: search_front_artists_path, local: true, method: :get, class: "search-form") do |f| %>
    <%= f.text_field :keyword, placeholder: "アーティストを検索する", class: "artistsearch_input", :size => "20" %>
    <%= button_tag type: :submit, class: "search_btn" do %>
      <%= image_tag "search.png" %>
    <% end %>
  <% end %>
  <div class="contents">
    <div class="row"></div>
  </div>
  <br>

  <div class="content_border">
    <h3 class="ranking_label"><span>Best ARTIST Ranking</span></h3>
      <% lastFavoriteArtist = 0 %>
      <% j = 1 %>
      <% @all_ranks.each.with_index(1) do |artist, i| %>
      <div class="flex">
        <div class="artist_box">
          <% if i == 1 %>
            <% lastFavoriteArtist = artist.favorite_artists.count %>
          <% end %>
          <% if artist.favorite_artists.count != lastFavoriteArtist %>
            <% j = i %>
            <div class="shadow_box">          
              <%= image_tag artist.image_id.to_s %>
            </div>
            <br>
            <br>
            <% if j == 1 %>
              <span class="best1_label">BEST <%= j %></span>
            <% elsif j == 2 %>
              <span class="best2_label">BEST <%= j %></span>
            <% else %>
              <span class="best3_label">BEST <%= j %></span>
            <% end %>
            <br>
            <br>
            <strong><%= link_to artist.name, front_artist_path(artist.id) %></strong>
            <br>
            お気に入り数：<%= artist.favorite_artists.count %>
            <% lastFavoriteArtist = artist.favorite_artists.count %>
          <% else %>
            <% lastFavoriteArtist = artist.favorite_artists.count %> 
            <div class="shadow_box">         
              <%= image_tag artist.image_id.to_s %>
            </div>           
            <br>
            <br>
            <% if j == 1 %>
              <span class="best1_label">BEST <%= j %></span>
            <% elsif j == 2 %>
              <span class="best2_label">BEST <%= j %></span>
            <% else %>
              <span class="best3_label">BEST <%= j %></span>
            <% end %>
            <br>
            <br>
            <strong><%= link_to artist.name, front_artist_path(artist.id) %></strong>
            <br>
            お気に入り数：<%= artist.favorite_artists.count %>
          <% end %>
          <br>
        </div>
      </div>
      <% end %>

    <div class="ribbon_wrapper">
      <div class="ribbon_content">
      <span class="ribbon">NEW</span>
      </div>
      <strong>New ARTIST</strong><p>　注目の新着アーティスト</p>
      <div id="new_artists">
        <%= render :partial => "new_artists" %>
      </div>
    </div>
    <br>
    <br>

    <h3 class="artist_list_label">
      <i class="fas fa-star fa_small"></i>
      <i class="fas fa-star fa_small"></i>
      <i class="fas fa-star fa_small"></i>
      &nbsp; ARTIST List &nbsp;
      <i class="fas fa-star fa_small"></i>
      <i class="fas fa-star fa_small"></i>
      <i class="fas fa-star fa_small"></i>
    </h3>
    <div id="artists">
      <%= render :partial => "artists" %>
    </div>
  </div>
</div>

app/views/front/artists/index.js.erb
if ("#new_artists") {
$("#new_artists").html("<%= j(render :partial => 'new_artists') %>");
} if ("#artists") {
$("#artists").html("<%= j(render :partial => 'artists') %>");
}

app/views/front/artists/search.html.erb
<div align="center">

  <h3>アーティスト一覧</h3>

<%= form_with(url: search_front_artists_path, local: true, method: :get, class: "search-form") do |f| %>
  <%= f.text_field :keyword, placeholder: "アーティストを検索する", class: "artistsearch_input" %>
  <%= button_tag type: :submit, class: "search_btn" do %>
    <%= image_tag "search.png" %>
  <% end %>
<% end %>
<div class="contents">
  <div class="row"></div>
</div>

  <% @artists.each do |artist| %>
  <% if artist.is_active == true %>
    <div class="flex">
	  <div class="artist_box">
	  	<div class="shadow_box">
		  <%= image_tag artist.image_id.to_s %>
		</div>
		<br>
		<%= artist.name %>
		<br>
		<a href="/front/artists/<%= artist.id %>" class="btn btn_viewmore"><span>VIEW MORE</span></a>

  <div class="artist_<%= artist.id %>">
    <%= render 'front/artists/favorite', artist: artist, locals: {artist: artist} %>
  </div>

	  </div>
    </div>
  <% end %>
  <% end %>
</div>

app/views/front/artists/show.html.erb
<br>
<div align="center">
  <div class="flex">
    <div class="shadow_box">
      <%= image_tag @artist.image_id.to_s %>
    </div>
    <div class="artist_label">
      <label class="btn btn_artistname btn-lg"><span><%= @artist.name %></span></label>
    <br>
    <span class="artist_<%= @artist.id %>">
      <%= render 'front/artists/favorite', artist: @artist, locals: {artist: @artist} %>
    </span>
    &nbsp; since <%= @artist.formation_yeah %>~
    </div>
  </div>
  <br>
  <br>
  <br>

  <div class="content_border">
    <br>
    <br>
    <div class="detail_space">
      <%= @artist.detail %>
    </div>
    <br>

    <a href="/front/communities/<%= @artist.id %>" class="btn btn_detail"><span><%= @artist.name %>のコミュニティページ</span></a>
    <br>
    <div align="left">
      <h5 class="artistshow_songlist"><span>SONG List</span></h5>
    </div>
    <% @artist.songs.each do |song| %>
      <div class="flex">
        <div class="new_artist_box">
          <div class="new_shadow_box">
            <%= image_tag song.image_id.to_s, :size => "150x150" %>
          </div>
          <br>
          <p class="new_artist_name"><%= link_to song.name, front_song_path(song.id) %></p>
        </div>
      </div>
    <% end %>
    <br>

    <div align="left">
      <h5 class="artistshow_rakutenlist"><span>RAKUTEN Shop</span></h5>
    </div>

    <% @items.first(3).each do |item| %>
      <%= link_to item.name, item.url, target: "_blank" %>
      ¥<%= item.price %>(税込)
      <img src="<%= item['smallImageUrls'][0] %>">
      <br>
    <% end %>
    <br>
    <br>

    </div>
  </div>
</div>