config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  get 'favorites/controller'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :customers, controllers: {
    registrations: 'front/registrations',
    sessions: 'front/sessions'
  }

  devise_scope :customer do
    post 'front/guest_sign_in' => 'front/sessions#new_guest'
  end

  root 'homes#top'
  get '/homes/about' => 'homes#about'

  namespace :front do
    resources :customers
    get '/customers/:id/follower' => 'customers#follower', as: 'follower'
    get '/customers/:id/followed' => 'customers#followed', as: 'followed'
    get '/customers/:id/favoriteartist' => 'customers#favoriteartist', as: 'favoriteartist'
    get '/customers/:id/favoritesong' => 'customers#favoritesong', as: 'favoritesong'
    get '/customers/:id/customerblog' => 'customers#customerblog', as: 'customerblog'
    resources :artists, only: [:index, :show] do
      resource :favorite_artists, only: [:create, :destroy]
      collection do
        get 'search'
      end
    end
    resources :songs, only: [:index, :show] do
      collection do
        get 'search'
      end
      resource :favorite_songs, only: [:create, :destroy]
    end
    resources :communities, only: [:index, :show] do
      collection do
        get 'favorite_index'
      end
    end
    resources :blogs, except: [:new, :show]
    post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
    post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
  end

  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'

end

app/models/admin.rb
# class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
         # :recoverable, :rememberable, :validatable
# end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  
  mount_uploader :image_id, ImagesUploader
  has_many :songs

  has_many :favorite_artists, dependent: :destroy
  
  def favorited_by?(customer)
    favorite_artists.where(customer_id: customer.id).exists?
  end

end

app/models/blog.rb
class Blog < ApplicationRecord

  mount_uploader :image_id, ImagesUploader
  acts_as_taggable

  belongs_to :customer
  validates :title, presence: true

end

app/models/chat.rb
class Chat < ApplicationRecord

  belongs_to :customer, class_name: "Customer", foreign_key: 'customer_id'
  belongs_to :community

  def self.created_via_speak(data, params, current_customer_id)
    chat = Chat.new(message: data["message"][0], customer_id: current_customer_id, community_id: data["message"][1])
    chat.save!
    MessageBroadcastJob.perform_later(chat, current_customer_id)
  end

end

app/models/community.rb
class Community < ApplicationRecord

  has_many :chats
  has_many :artists
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :nickname, presence: true
  validates :password, presence: true
  validates :password_confirmation, presence: true, unless: :guest?

  has_many :blogs
  has_many :chats
  has_many :favorite_artists, dependent: :destroy
  has_many :favorite_artist_artists, through: :favorite_artists, source: :artist
  has_many :favorite_songs, dependent: :destroy
  has_many :favorite_song_songs, through: :favorite_songs, source: :song
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_customer, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_customer, through: :followed, source: :follower # 自分をフォローしている人

  # ユーザーをフォローする
  def follow!(customer_id)
    customer = Customer.find(customer_id)
    if self.following?(customer)
      raise ActiveRecord::RecordInvalid
    else
      follower.create!(followed_id: customer_id)
    end
  end

  # ユーザーのフォローを外す
  def unfollow!(customer_id)
    customer = Customer.find(customer_id)
    if self.following?(customer)
      follower.find_by(followed_id: customer_id).destroy!
    else
      raise ActiveRecord::RecordInvalid
    end
  end

  # フォローしていればtrueを返す
  def following?(customer)
    following_customer.include?(customer)
  end

  def remember_me
    true
  end

  def self.guest
    find_or_create_by!(last_name: '山田', first_name: '太郎', last_name_kana: 'ヤマダ', first_name_kana: 'タロウ',
                       email: 'guest@example.com', nickname: 'ゲスト様') do |customer|
      customer.password = SecureRandom.urlsafe_base64
    end
  end

  mount_uploader :image_id, ImagesUploader

  private

  def guest?
    nickname == 'ゲスト様'
  end

end

app/models/favorite_artist.rb
class FavoriteArtist < ApplicationRecord

  belongs_to :customer
  belongs_to :artist
  validates :artist_id, uniqueness: { scope: :customer_id }

end

app/models/favorite_song.rb
class FavoriteSong < ApplicationRecord

  belongs_to :customer
  belongs_to :song
  validates :song_id, uniqueness: { scope: :customer_id }

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :songs
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "Customer"
  belongs_to :followed, class_name: "Customer"

end

app/models/song.rb
class Song < ApplicationRecord

  mount_uploader :image_id, ImagesUploader
    
  belongs_to :artist
  belongs_to :genre

  has_many :favorite_songs, dependent: :destroy

  def favorited_by?(customer)
    favorite_songs.where(customer_id: customer.id).exists?
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_customer!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :null_session

  def after_sign_in_path_for(resource)
    case resource
    when Customer
      front_customer_path(current_customer)
    when AdminUser
      admin_comments_path
      stored_location_for(resource) ||
       if resource.is_a?(AdminUser)
         root_path
       else
         super
       end
    end
  end

  def after_sign_out_path_for(resource)
  	root_path
  end

  unless Rails.env.development?
    rescue_from Exception,                      with: :render_500
    rescue_from ActiveRecord::RecordNotFound,   with: :render_404
    rescue_from ActionController::RoutingError, with: :render_404
  end
 
  def routing_error
    raise ActionController::RoutingError, params[:path]
  end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana,
                                                         :first_name_kana, :nickname, :image_id])
    end

  private
 
  def render_404
    render 'error/404', status: :not_found
  end
 
  def render_500
    render 'error/500', status: :internal_server_error
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  skip_before_action :authenticate_customer!

  layout 'home'

  def top
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :customer
  end

  def resource
    @resource ||= Customer.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:customer]
  end

end

app/helpers/front/artists_helper.rb
module Front::ArtistsHelper
end

app/helpers/front/blogs_helper.rb
module Front::BlogsHelper
end

app/helpers/front/songs_helper.rb
module Front::SongsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MUSIC fanS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <% if customer_signed_in? %>
    <header>
      <div><%= link_to 'Mypage', front_customer_path(current_customer.id), class: "edit_link" %></div>
      <div><%= link_to 'Artists', front_artists_path, class: "edit_link" %></div>
      <div><%= link_to 'Songs', front_songs_path, class: "edit_link" %></div>
      <div><%= link_to 'Community', front_communities_path, class: "edit_link" %></div>
      <div><%= link_to 'Blog', front_blogs_path, class: "edit_link" %></div>
      <div><%= link_to 'Logout',  destroy_customer_session_path, method: :delete, class: "edit_link" %></div>
    </header>
  <% end %>
  <div class="container_cover"> 
    <div class="container">
      <body>
        <%= yield %>
      </body>
    </div>
  </div>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MUSIC fanS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="js/jquery.bgswitcher.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 
  <body>
    <%= yield %>
  </body>
</html>